apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-access-key
  namespace: cert-manager
spec:
  encryptedData:
    key: AgC1F99q5/OmNkJmbewlBDD8d6fQjfZ6dCaZzeSufvd+U+PfcjVhZ3iqvSodFjKh76fc2oWZAOUYHlk2WFHr469UTeiAv7Wq4q9SvcmUgR6JjSJpfQotGVX2tDtYV1b5etvpFNDOjthsMzzpzUnU4DMPKy9mPhis//0C+iH3NXrkLDpfq/XwpuhL306Bjknkx6ZZHUB1im4B3TyMlaEaXTv66YQFBKtwORE8KhNaXKwomBKZKdMd/rax40lYvAv8Ikd1nFwC8uZKqAdRMPexbiZfE4kmSD5j88wRsxmoknFpdXKkNg7C/D19eUlap9VgvgcNju+HRcaV/EcnHL7pVZaMRhv+itCpymlu6lbh/j33KNy+8tg7aWoTqFzwcQV9o686FqnftcVyZ4BmObxUxF8K03mxPHaarq7BqXZPyPA/rxH9jP1pHpAmRbCz8sdW/AG1bngBpuXhTRjyF2Z23t8YzkeRKBUiXtfX91WcBp6jV5QJJjxNMBhCWFJdyU2KrNWLM15Scoevo30lGoLxBALVZvYM3rAJmIZtKX2WZbsTmQjz6ebYqQ5HSuW5Wy9NeI9Rd/y6CGy+yqhXXAmbMzdPl/W/mkE7UVzkNSKkUXKW9vPNySdfsk5uxvtbI9PXf0GmVCwq5aYqJFAMjfgILHasAUq8yQOaNViOrNe4cIMSZ6Wx6c6iSprjg7SIBtgC5fItbZB0JdWSwjRbrMr3SZFOCsAVZlNTy23e9JDv9koQ6HXjUQ0WVv8b
    keyId: AgAv0iPIIRSE32+woGCb0h1o/spZaw7pf1jederHesDMUlw9R9OzVOZIFVT6aBomEUGDtZvXeeHDg+bcern15CG7iQpSae+ZcJ9NNYOXV34uv2yJfbE//eRI4vQuGQRDeNP9dk37JQKsVzP/YBb48AkGQ6KlWI4JvbUL1vuEjK96ya3Phm441+yLrmqDGBGq/u2cerrI01xACgNyMjEjmq3iSNCja1EgW3HmMCCd7e4K/kb23BvyPyoLZdCTXV1nU1isbBeA3FNt0bs85EFJ9ou2UQ6QlENS2aieRGli2zpP1PkXEJCxJiAZCJU+WbpPGg5kmTSQIdyyXYJS4zJt20vmtv3kSYwC9mQ6xDuhVPQTIz3FuQwSAG1KZxGAG3jXRug+UkcqWBMajlJgU/Wd39S2OQUCEsUMkjjTL7KNPNXPAmXIpEbuzFwovPkbfaE+Kxc8Ek+uCHNpr3yVZY87M3y11Xs9znVJJSYRqRhm/U1PN5b96hAkJfJhsod5acoj/YhUJ1/2PpxuixwuJ5r3dGOvxk5P/kSodvkUShYxWUydYxcaUPWHdUr9xEB65FpcE+7/KUXZrNfxpjIxhKy+ok19vJz0Cd37hXTEE9I/6qwuenKY9WTQJn4TG20uT2S/CWdDzAhPbpVnhgaIUw4+NNyQpFicH7m0fy1cuG7n2Oi7MoPEuojAeCONGSLnBqt3O4EDhTwZNKkQwaGHE0/VNiUz8hZ1Kg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-access-key
      namespace: cert-manager

