apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-aws-prod
spec:
  acme:
    email: stefan.wiedemann@fiware.org
    preferredChain: ""
    privateKeySecretRef:
      name: lets-encrypt-prod-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
          - "dome-marketplace.org" 
      dns01:
        route53:
          region: eu-central-1
          hostedZoneID: Z09429351HAAB47Z628ZL
          accessKeyID: AKIA272Z63S3KLVSDUQZ
          secretAccessKeySecretRef:
            name: aws-access-key
            key: key
