apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-knowledgebase
  namespace: argocd
  labels:
    purpose: knowledgebase
spec:
  destination:
    namespace: knowledgebase
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ionos_dev/knowledgebase/mysql
    repoURL: https://github.com/BazRoe/dome-gitops.git
    targetRevision: bookstack_deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true