apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.dome-marketplace.org
  # explicitly set through rbac
  admin.enabled: "false"
  dex.config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID:  65555cc661699aa6e33e
          clientSecret: $github-secret:clientSecret
          orgs:
          - name: dome-marketplace