apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: access-node
  namespace: argocd
  labels:
    purpose: marketplace
spec:
  project: default
  source:
    repoURL: https://github.com/DOME-Marketplace/access-node
    targetRevision: HEAD
    path: ionos_sbx/marketplace/access-node
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: marketplace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true