apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: marketplace
spec:
  encryptedData:
    mongodb-root-password: AgCHuBUKN358bmOA717skZNGnGyd/HGQ1wbLJzf/6R3sRdeIBoWg9MKaSxpJL5l5WOiE7ZT3zxJMyi5qhY5DoHQaMfrsbsdWsW7J1Jo2d5HoJi9z97JxQ/tbJW00LIJYutfQLFhNzzgY+RAyy0RvjBrZCWOYUHHvxMZUqht9BDY+VfwzVrvrM1c7RAlU5YO6RumNHYwFIDQaErfMLS6De0n7dd3TeAzmRfXqy9o0+sN+pW5HBUpxaLm7Dy33gVaHD6rJn5EiyfJHD7NeKps/GjLNSe/Su7ob/3R7TY02e/DTE9hJ9OS7/tD3Z51S0bjUiKAn+CwWg9vZ6jIdtT+n8mYGznhCUgnhhh0kKd53RLtPZRDtWoFk+46sOzs5Y78l/JdLN1IgkdJTK/J++6Q6vQ8U9bL4b8JYaFxwbfZhVc5KagH2ZSjyKxklEG/u414yA/RLYEsx+sezAjkez8/9T+DvBrwoLK++So6rh7M3Dq7bnANGeJ+/iiBI30Qv2zGzj14bvNF3CMQIiO4c1w8m0xVR3W9BpwdQOQk8fMR+TEoin5EtUs43EZT4IH42XwlS9IDiMT6CErdVVI8rvSWU+6FC/9mAzqlhU5y1Od7m8YP3jcPVS0QJvi+XCeelA+asl6uz+ns3b0OvD01iEs/Hb7B6kpY4mjvLaEhS/GOpYm74el//SlifmeZhEpVZmS1DyXV7jcTKbAZcsOVK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: marketplace

