apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-storage-uploads-pvc
  namespace: knowledgebase
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi