apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-storage-uploads-pv
  namespace: knowledgebase
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/path/to/bookstack-storage-uploads"