apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    purpose: infra
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ionos/external-dns
    repoURL: https://github.com/wistefan/dome-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true