apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-access-key
  namespace: infra
spec:
  encryptedData:
    credentials: AgCGSUVBgptMM3F+YN9zzGeMoMxFDHN+fmJiZPz9ErI8sWwP5dkBwaJWugjuD/ErUN9oLyLXxuOWjOZhYG3d+AdIC/eLqE9Q5n7CCRXWI4Dg2PD5vQghRUJRe5oqa+FTupK3on/wVxKm0+G52WHOFhYbU8cTBHfeQ51Uce91OmokITb6jVEtZbtrvjWpXanNNLspVmVYVGimTpx/VsPWSBYJs3EmLOeA0X/IRqX7JrB6oI3TUcNhoF0de6NxQcpVxZEV0lkKezCYxw4uqH6J2NNtyfMC9OUh0TuCPFxm9LT0Bv4ZtRx6lr9+tmo7iAUQAERbn5uiXRySeI6Nst7ejZVAfy+F3oDhdYnU0MxVnhuYasUin+7itHDwqXgVmIvXNUmaFdqmypZ8YXl3dWI0q02ZxaXQAeNoCsoMJ3pPbQGndR5IyyDYPup/LUTj1MiOf5mO7niqRGnbkWXWOoRZohd9NBK7FbBwuSHDPLB3+QmVHmP3jXO47buT2cJVI+K/M4H5zIw9aTEiG6rbJz2GVxxBxOCiOjkrPXtR9GH1EE5dA1DJyrYtBM0VzU1Nvea/iJvmaPOLSZDAcBUrtaRIjp1al3fsCSSA5YbQvxg9x8Q4nHYlpSQ+89bUTiSulxSB4OGPcI5MHX0I+rzifgJr26t2SJD5grto9obcCfX+M0IeL6KgvYCcdJ+hI0+UAMH0IMA0hpAjksJazXwh6vyKXcIye/TqPrt9rAUhyMqKeNQqtPT1ZebcU2m7Jls8ZVsJOTjhSnqKRX1lqZpG3Jj9GRROCi5aRU/JePPl7X0H9ntAmKE4Sb7B72MbO+NlOqD/aM1HNztYwauwI8tqvrpHeBZb9iR2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-access-key
      namespace: infra

