apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-access-key
  namespace: infra
spec:
  encryptedData:
    aws_access_key_id: AgB4xR2FM1Z3ji1nSXLWHVizHLh6Rgwa9utdMo5HpXOSMvMmvojeIMpbTM0FMzXQ1pXkc3s2M3/n8n+ZBLTCfscZ4Fm5egQYoF2XT3uOZO+eiQIqP6P6mz/CLZ6e0JWZcSVQxKFJ6donkihNR++Mi/fIadgwWL586Z7QrooIFa3PUnFhgCzNUEqjW+hjUmN6zLFIp/YTsLGzxBweESkArX3nef2jKtz6N3kOx0JrM0pMeK6CK07hiW0wJJibmmqtej+dC07369oGlPjfiyyWm5miyHp4yaGv59KQwqiTrAkXwh+G/CHn5sEwYn09SDfsZKk4wpJma+I4f2DjQkVFvwtdGGTMAMszWBBeYBsJPjHx1j0aVmlqiLZNHBzmk1WmkEfm9GHgd43LRAFXn5w+leyVp6opgwW5SbtGI4fo3hmjiz6kthadpLdFlsgsHK9s2kE8kw5ZHscZPLjCKI7h2+ZtegmwHgPpJOPhm3mx73KTP3toeXp3UuZEYt1B/48B8ky23agx6WB6e+Z/uz9rdLgMWmrG26LwiDGGdOG0S/3DqlDQ0chn9LmKUPbc5cGUDMk3ziNG7FZfpYYir+c79HfbhZQGkhgIsatoYEmqG9A0JvLjsfIYp3QBZ4566rU1DbGhdolbrCV4cNsSqorPuBfJLmqibNNoXc3s9wJqjJkvEUGnLODft0BziL81Q10FBLsJcdqJ8iru2Q3I21i5aUSN7tsShg==
    aws_secret_access_key: AgAkVfpCtVVBX7hsgUEAH93kfP6DafteCGt52laiReRHBHTuopJ6av0PR1XomgRYrhbFnhm6srBZiLx6jH4mkitRjqZmuAAqD7QG48GY0UobnrHC0BG7w005hnYQt7vOYJHZvi+vASwNFdT65xuon1fiKPMA1XyO9xFZELA6noxjx0Gbvk8YIcB0gMQEcJ77nIulrqOWHZGfEm8f0EVbn4wbeMJE0k/VahZ2f/hM/mpCIZWRtG5CilKtxbX4+xLjiVzTsGxTouIbweUS25PRNC3RDtAr7byucpdTybgu7H5nDDBAWcG1Irot6txjGN70z2Z5bAdZ8IzerKU/KtM4sCXYwU1wNyfc/QdDJ7lAKutjWnsELqZDO86gGWK5fgvvB+Mg0+cxscb/whRUT2K8zr55Ow+BrBOHzg6EmoUsI4caGhv/bWVnKjz8pmo9bZfpbFWuoydQvJzfn8eemKzb9r4ebiuWW15raNEZWT6IdE96Ssi4yiL7n9zB7D6Xj0DucNw2K+10fQAAxoTG0frBVydu7X65yw5yEP23k6F03yRk7NzQmdzT4oyzF+mydF1y2o/snJOEBOx/ZDoFzvxM3Mgba3k5tEQLDTiNwV73993rJH3gYmAiTbd0pKh9nbQzZNSmjAYpk5MxxL/YebG2BrbDpvyRImactmBDnLBNubQ2N6n0JAs9az7XDZ2Ng+LDFOD/WC0N7VPBiDucTn14NylGC8zAyopA5Ak/sPnK+6uBY+5QcslYDtxL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-access-key
      namespace: infra

