apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kong.dblessConfig.configMap }}
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:

      - host: "scorpio"
        name: "orion"
        port: 1026
        protocol: http
    
        routes:
          - name: vc
            paths:
              - /scorpio
            strip_path: true
    
        plugins:
          - name: pep-plugin
            config:
              pathprefix: "/scorpio"
              authorizationendpointtype: ExtAuthz
              authorizationendpointaddress: http://pdp-trust-dsba-pdp:8080/authz
                
          - name: request-transformer
            config:
              remove:
                headers:
                  - Authorization
                  - authorization
