apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: infra
spec:
  encryptedData:
    adminPassword: AgBWQHPZruBE6Gn+RcN9cucZkyUIxrB7T5JBbvwMZ6Yb/+pQg6B9mXWU9ATt/YrHqbD/62IDiqPLHNm9ApMgExyzWkd5lUWRoDAXue6zQfrCabS0+88VqBOCaanO/F45/jOPpToKHsdAG0a+gMntn5xOR7WH18xhHT8+jWLnVggeFOhz0ACkd0ZZpO0MMjV+U0bYHumaFgVvnrpFd5ULsj3FC4DXQjMwTeDMKNMxgHJupbkQsfPn2iukHRwvAVBlD1zNgsH2uz3m3/eYjQNaxuOhWztdRZn1Vm5qPlCT2RrTai+kECCqFr76z1j5SKGV1dixE17QOb2vxsboxVscWO8FQzLJIt7Z1c8xE/haYDqQnRrViIbUfc2AV498ASLrS0eCJtf/9Ky6Wq7J+2nFGtcZTkA/bJSYeyPAo6/FarrKA0Iuhhc8n8PjOm3nLHdyM6nHR0SHsNhq6HAfBfCLa+DbnAp1Hs9T3FQ97NVq4SQ70HZY8TRLqsSEHXrFJ5UPDx3uo1+Pke8g/xDA3+M/3dfhIGDj3UCwZaWq4Oppfb+2mCqHZtHEq+Cc2EvEspTamwrKFHadwYOreZOC+gvsMTPToDk+knq4O+BtqpiGoZJko76MS/O+Rwz0fEz4F2AVZhmkg1vfskS07GlDgQZJhYVc/h8ZDEZzpw/lXBw2vrtjNzRHoa91yjJ5GG/w6VHTczzi3H6f1OWGNxeJ4PV7iw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: infra
    type: Opaque

