zammad:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dev-issuer
    hosts:
      - host: ticketing.dome-marketplace.org
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: ticketing-tls-secret
        hosts:
          - ticketing.dome-marketplace.org