{{- $api := index .Values "tm-forum-api" "apis"}}
{{- range $api -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "tmforum.fullname" $ }}-{{ .name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tmforum.name" $ }}-{{ .name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tmforum.fullname" $ }}-{{ .name }}
  
  minReadySeconds: 30
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600.
  progressDeadlineAbort: false

  strategy:
    blueGreen:
      activeService: {{ include "tmforum.fullname" $ }}-{{ .name }}
      previewService: {{ include "tmforum.fullname" $ }}-{{ .name }}-preview
      previewReplicaCount: 1
      autoPromotionEnabled: false

      # prePromotionAnalysis:
      #   templates:
      #   - templateName: success-rate
      #   args:
      #   - name: service-name
      #     value: guestbook-svc.default.svc.cluster.local

      # Post-promotion analysis run which performs analysis after the service
      # cutover. +optional
      # postPromotionAnalysis:
      #   templates:
      #   - templateName: success-rate
      #   args:
      #   - name: service-name
      #     value: guestbook-svc.default.svc.cluster.local

---
{{- end }}