apiVersion: v1
data:
  aws_access_key_id: QUtJQTI3Mlo2M1MzRFVLVDdTTzM=
  aws_secret_access_key: LzdGLzBSWXJTcGp6clJpNXpOR2tRa2Fjc0RxNjd5blFRMHBFRFpGSg==
kind: Secret
metadata:
  name: aws-dns
  namespace: cert-manager
type: Opaque