# Organisation DID
did: did:web:dome-marketplace.org

ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-aws-prod
  class: nginx
  host: dome-marketplace.org
  tls: 
    enabled: true

# Walt-id config
vcwaltid:

  # Image
  deployment:
    image:
      repository: quay.io/fiware/waltid
      tag: 1.14.1-SNAPSHOT
      pullPolicy: Always

  # API config
  api:
    core: 
      enabled: true
    auditor: 
      enabled: true
    signatory: 
      enabled: true
    custodian: 
      enabled: true
    essif: 
      enabled: true

  # Persistence
  persistence: 
    enabled: true
    pvc:
      size: 1Gi

  # List of templates to be created
  templates:
