apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dome-trust
  namespace: argocd
  labels:
    purpose: trust-anchor
spec:
  destination:
    namespace: dome-trust
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications_dev/dome-trust
    repoURL: https://github.com/ivanligot/dome-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true