apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-ionos
  namespace: argocd
  labels:
    purpose: infra
spec:
  destination:
    namespace: external-dns-ionos
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ionos_dev/external-dns-ionos
    repoURL: https://github.com/ivanligot/dome-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true