apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: orion-ld-rollout
spec:
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: orion-ld
  
  minReadySeconds: 30
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600.
  progressDeadlineAbort: false

  strategy:
    blueGreen:
      activeService: orion-ld
      previewService: orion-ld-preview
      previewReplicaCount: 1
      autoPromotionEnabled: false

      # prePromotionAnalysis:
      #   templates:
      #   - templateName: success-rate
      #   args:
      #   - name: service-name
      #     value: guestbook-svc.default.svc.cluster.local

      # Post-promotion analysis run which performs analysis after the service
      # cutover. +optional
      # postPromotionAnalysis:
      #   templates:
      #   - templateName: success-rate
      #   args:
      #   - name: service-name
      #     value: guestbook-svc.default.svc.cluster.local