apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-connector
  namespace: argocd
  labels:
    purpose: marketplace
spec:
  destination:
    namespace: marketplace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ionos_dev/marketplace/connector/postgres
    repoURL: https://github.com/ivanligot/dome-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true