keycloak:
  service:
    type: ClusterIP
  logging:
    level: INFO
  replicaCount: 1
  auth:
    existingSecret: keycloak-secret
    passwordSecretKey: keycloak-admin
    adminUser: csAdmin
  serviceAccount:
    create: true

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: cs-identity.dome-marketplace-dev.org
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dev-issuer
    tls: true
    
  extraEnvVars:
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_LOG_LEVEL
      value: INFO
  
  postgresql:
    enabled: true
    auth:
      database: keycloak
      existingSecret: keycloak-secret