apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-cert
spec:
  secretTemplate:
    annotations:
      cert-manager.io/allow-direct-injection: "true"
  secretName: webhook-tls-sec
  issuerRef:
    kind: ClusterIssuer
    name: self-signed
  commonName: webhook-server.marketplace.svc
  dnsNames:
    - webhook-server.marketplace.svc