---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: desmos-postgres-secret
  namespace: marketplace
spec:
  encryptedData:
    postgres-password: AgByBSIEuH7w/mSgG/RWTGX0wCO+0XfQiFYH+WpN47Y00lZlNUKoj839E7qAN9HfY3BEXeIeseT8yifmbPXlUGzYpiqgEljZurH50As+7z2o2ZSG30309iYvliPcnH6arYFKQEZGfHdtwxa74kyJp1siyNToXxmdGG0LD9ZEGAJhpv8cRrSGSpRJSkzHSE4dzc9wez0zVODSwHZWrhPM4Mt93VBVYk8H/zrAO8OSraLXj1wx8QdKoivDuU4LrYfbMt+WWk5SajFCxDzJf9sfS2f6aHBRJVD5SYXH4qCttGv1gVyS/sBNyHNeKY3gCwHPt2e3rlgszpKYqET7nGvPvfOUf2ny93k1qL34cKm11Z7wew5L54bjWxMa3T8qTQHmGDwRjjjeimtUB8zXI60BatLgOBxk/8EWHyDp58wSmeAblUAtPJjreQB4mqkhdi2BHBhL2lzU4RpkhwHqdRtEGSksgptZQ9jAABm9TrXTJFEIKJbt4d1deOkWs98mQ8A80NMcZl+SvDpCVpKyqlSGjrFeZzVsAYEV4eNvc+I4Fe3jDR7M8EnCEjA/NzjXJnpu5TVoGq6l/lhOHEq6XlDAJFI2ksX0lU9VP1xALY8chKB8ibtAD4n8Zq+aheO7NA6Zbu2fCmRhq8QsIU1mbVZ433+xI+qZcQH3mjuTivuJZcIXGkRWbHGgdHDcWW9Fa/7ceMJvzScpbUTBOQ==
  template:
    metadata:
      creationTimestamp: null
      name: desmos-postgres-secret
      namespace: marketplace
