apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    purpose: wallet
spec:
  project: default
  source:
    repoURL: https://github.com/DOME-Marketplace/dome-gitops
    targetRevision: HEAD
    path: ionos_sbx/wallet/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: wallet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true