apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-connector-core
  labels:
    app.kubernetes.io/instance: blockchain-connector-core
    app.kubernetes.io/name: blockchain-connector-core  
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: blockchain-connector-core
      app.kubernetes.io/name: blockchain-connector-core  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: blockchain-connector-core
        app.kubernetes.io/name: blockchain-connector-core
    spec:
      containers: 
        - image: in2kizuna/blockchain-connector:v1.0.0-SNAPSHOT
          name: blockchain-connector
          env: 
            - name: DATABASE_URL
              value: "r2dbc:postgresql://postgres-connector:5432/mktdb"
            - name: FLYWAY_URL
              value: "jdbc:postgresql://postgres-connector:5432/mktdb"
            - name: SPRING_CONFIG_LOCATION
              value: /config/application.yml
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
          - mountPath: /config/
            name: custom-config
      volumes:
        - configMap:
            name:  blockchain-connector-core
          name: custom-config