apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketplace
  namespace: argocd
  labels:
    purpose: trust-anchor
spec:
  destination:
    namespace: marketplace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications_sbx/marketplace
    repoURL: https://github.com/DOME-Marketplace/dome-gitops
    targetRevision: env_production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true