external-dns:
  env:
    - name: AWS_SHARED_CREDENTIALS_FILE
      value: /.aws/credentials
  volumeMounts:
    - name: aws-credentials
      mountPath: /.aws
      readOnly: true
  volumes:
    - name: aws-credentials
      secret:
        secretName: aws-access-key
  txtOwnerId: ionos-dns