name: Deploy to the demo namespace

on:
  push:
    branches:
      - 'main'

jobs:

  deploy:

    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v1

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy applications
        run: |
          cd applications
          # apply all apps in the apps folder
          find . -name '*.yaml'  -exec oc apply -f {} \;
          # label them for better filter machanism      
          find . -name '*.yaml'  -exec oc label deployed-by=fiware-gitops-ci --overwrite -f {} \;